# Generated by Django 5.1.1 on 2024-10-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_profile_orderplaced_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
