# Generated by Django 5.1.1 on 2024-10-24 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_orderplaced_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='transaction_id',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], max_length=20)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='app.orderplaced')),
            ],
        ),
    ]
