# Generated by Django 5.1.1 on 2024-10-24 11:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_orderplaced_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='order_id',
            field=models.CharField(default='default_order_id', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orderplaced'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
