# Generated by Django 5.1.1 on 2024-10-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_orderplaced_order_id_alter_customer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
