# Generated by Django 5.1.2 on 2024-11-05 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_customer_bio_customer_date_of_birth_customer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='profile_picture',
        ),
    ]
